### ISSUE TITLE
Python coloring breaks on raw string ending with backslash

### ISSUE THREAD

**Issue by Cavaler** [colorer/Colorer-schemes#103]
Строка вида:
r"\\VOTTS-NAVTECH\Install\\"
не воспринимается как законченная raw-строка, как следствие съезжает вся подсветка после нее

**Comment by ctapmex** [comment]
Duplicate of #100

**Comment by ctapmex** [comment]
Duplicate of #80

**Comment by ctapmex** [comment]
fixed
