### ISSUE TITLE
Отгрузка новых версий

### ISSUE THREAD

**Issue by ctapmex** [colorer/Colorer-schemes#124]
@nightroman 
Роман, давай  обсудим тему быстрой доставки новых версий, поднятую в #123 
что имеем сейчас:
1. FarColorer выпускается раз в N месяцев/дней, когда накопились какие-то изменения. При сборке дистрибутива берется последний готовый дистрибутив из схем.
2. Дистрибутив схем собирается так же раз в  N месяцев/дней, когда накопились какие-то изменения
3. в Far при ночных сборках встраивается по умолчанию последняя версия FarColorer . Т.е. со временем схемы устаревают.

Это базовый набор схем, который есть в поставке Far.
FarColorer предоставляет возможность указать путь до своего набора схем. Как до полного, так и до "дополнения".  И у меня есть ощущение, что многие пользуются этим. Как по причине "не нравятся текущие настройки", так и по причине "редкой отгрузки новых версий". 

Я не хочу возвращаться к схеме, когда far при ночной сборке делал полную сборку FarColorer с схемами. Это долга сборка из-за зависимостей. Это постоянная необходимость адаптировать эту сборку под изменения, не имея там прав/возможности проверить. И т.п.. Уж лучше будет браться готовый дистрибутив.

Вот в такой схеме , как бы ты видел обновление схем после изменений ? С какой периодичностью? Тебя не устраивает вариант держать в настройках свой набор схем ?
хочу понять ожидания/требования.

**Comment by nightroman** [comment]
Надо немного подумать, если что найдется сказать. Пока отвечу на это:

> С какой периодичностью?

По мере изменений. Задержка не более пары дней после принятия их. Да и принятие PR тоже медленно происходит (иногда).

> Тебя не устраивает вариант держать в настройках свой набор схем ?

*Меня* устраивает. Но дело не во мне, и даже вообще так не стоит вопрос.

1. Другим пользователям эти изменения скорей принесут пользу (пусть они даже и не узнают).
2. Главное: мне же надо протестировать именно в Фаре мои изменения, а не только в локальном сетапе. Когда проходят недели / месяцы, то можно и не заметить момент, когда пора тестировать. Или уже забыть, что именно менял и что проверять.

**Comment by ctapmex** [comment]
посыл понял. буду думать

**Comment by ctapmex** [comment]
в ночных сборках far используются последние сборки схем

**Comment by nightroman** [comment]
отлично, спасибо
