### ISSUE TITLE
shell scheme expects closing parenthesis where it is not required

### ISSUE THREAD

**Issue by russiandesman** [colorer/Colorer-schemes#139]
Consider the following example:
```
if [ x"$SOMETHING" = x ]
then
# comment
    SOMETHING="colorisation works"
fi
export SOMETHING=`echo $SOMETHING|sed -e 's/THIS(//'`
# This is a comment but colorisation doesn't work
export THIS_IS_NOT_HIGHLIGHTED=
command_which is not highlighted
```

Colorisation stops working after seeing opening parenthesis in sed's regexp. Parentheses are not special symbols in sed and do not need to be paired, it is pretty common to find something like "text (".

It would be great to fix this.

**Comment by ivanshatsky** [comment]
Just for additional information.
As far as I understand, strings in form of `s/.../.../` assumed to be PCRE-compatible regular expressions.
However `sed` (at least GNU `sed`) operates in terms BRE and ERE (see [BRE vs ERE](https://www.gnu.org/software/sed/manual/html_node/BRE-vs-ERE.html) GNU `sed` documentation chapter).
The following lines
`sed -e 's/THIS(//'`
and
`sed -E 's/THIS\(//'`
are equivalent, however the first one contains a BRE and the second one contains an ERE (most or less similar to PCRE).
The second line will be colored correctly while the first one won't.
I guess to fix this issue an additional BRE syntax should be described, and we need to know somehow what kind of regular expression (ERE/PCRE or BRE) should be expected at particular place. Maybe it could be done parsing `sed`/`grep`/etc. switches, however I'm afraid it can't be fixed an easy way and will complicate the existing scheme a lot.

**Comment by ctapmex** [comment]
fixed in https://github.com/colorer/Colorer-schemes/releases/tag/v1.2.0.36
