### ISSUE TITLE
Подсветка в Markdown

### ISSUE THREAD

**Issue by johnd0e** [colorer/Colorer-schemes#149]
Сейчас подсветить **слово**, после которого (без пробела) следует знак _пунктуации_, можно только закончив подсветку после знака пунктуации.

На самом деле маркдаун этого не требует, пример текста выше, исходник ниже.

```md
Сейчас подсветить **слово**, после которого (без пробела) следует знак _пунктуации_, можно только закончив подсветку после знака пунктуации.
```

Просьба исправить схему.
@nightroman

**Comment by johnd0e** [comment]
Похоже что-то недоисправлено.

**Comment by nightroman** [comment]
![image](https://github.com/colorer/Colorer-schemes/assets/927533/6f717fda-fc74-470f-a541-95f82c93b3b0)

**Comment by johnd0e** [comment]
@nightroman 
```md
- Сейчас подсветить **слово**, после которого (без пробела) следует знак _пунктуации_, можно только закончив подсветку после знака пунктуации.
```

Исправляется если внести такое же изменение в `<block scheme="StrongSpan" region="EmText"`.

(там и другие регионы с идентичными регэкспами, не исключено что из все надо под одну гребёнку)

**Comment by nightroman** [comment]
Да, было еще 3 места с подобным исправлением, спасибо. Исправил, пул ресквест отправлен.
Для истории, всего 4 таких места и регекспа:
1. paragraph with `_`
2. paragraph with `__`
3. list item with `_`
4. list item with `__`
