### ISSUE TITLE
Markdown: раскраска и html-тэги

### ISSUE THREAD

**Issue by johnd0e** [colorer/Colorer-schemes#155]
Текст, заключённый между целым рядом тэгов, парсится как макдаун, и должен быть раскрашен соответственно.

Пример:
- **bold**, _italic_

<details>

- **bold**, _italic_

</details>

Исходный код:
```md
- **bold**, _italic_

<details>

- **bold**, _italic_

</details>
```

В настоящий момент `markdown.hrc` не учитывает этого, и не красит содержимое между \<details\>, и очевидно многими другими тэгами.

Не исключено что между диалектами маркдаун тут вохможно некоторое отличие, но по крайней мере **gfm** есть чёткая спецификация.
См. пункт 6: https://github.github.com/gfm/#html-block

@nightroman

**Comment by johnd0e** [comment]
> решение - не поддерживать хтмл. Вряд ли я его поменяю

Это ничего, значит просто обменяемся мнениями)


> ...и наличие пустых строк после чего-то в качестве критерия закрывания блока

Этот критерий можно ослабить, исходя из двух следующих соображений:

1. Для завершающего тэга пустая строка не всегда обязательное требование, может быть также:
    > ...or the last line of the document, or the last line of the [container block](https://github.github.com/gfm/#container-blocks) containing the current HTML block

2. Перед колорером вовсе необязательно ставить задачу строгого контроля чем там завершается тэг.
   Сейчас этого не делается, содержимое просто не красится.
   Я предлагаю в этой же ситуации содержимое красить.
   Для обоих случаев (и сейчас, и если моё предложение будет принято) будут граничные случаи, в которых тэги будут восприниматься иначе чем в спецификации, но беды в этом нет, потому что
   a) Полностью корректный код будет в итоге раскрашен верно по крайней мере в 99% случаев
   b) Не полностью корректный код будет тоже раскрашен колорером, и отражать намерение пользователя.
      То что рендерится он может иначе - это не проблема колорера.

**TL;DR:**
- Предлагаю продолжать обрабатывать html-теги как сейчас (не пытаясь воспроизвести спецификацию во всех деталях), но текст внутри тэгов из пункта 6 красить как маркдаун.
 - Предлагаемое изменение улучшит experience по очевидным причинам, и я пока не вижу ни одного потенциального кейса, для которого произошло бы ухудшение.

**Comment by nightroman** [comment]
Попробуйте, покажите, что получилось. Если результат хороший, и ничего особо не отвалится (мои способы тестирования), то почему бы и нет.

**Comment by johnd0e** [comment]
> Попробуйте, покажите, что получилось.

Э.. Кхм..
Для меня hrc что китайская грамота, поэтому сложновато выходит попробовать.

**Comment by nightroman** [comment]
Тоже в этом не как рыба в воде. И работа над схемами идет с перерывами, все забывается. И маркдаун не самая простая схема.

**Comment by johnd0e** [comment]
Спасибо вам за неё!

**Comment by nightroman** [comment]
Понимая важность тегов типа details, готов попробовать хоть что-то. Например, можем пропарсить теги типа 6 как самостоятельные и полные, а не блочные конструкции, начало и конец не связаны, конечно. Тогда все, что вне них, внутри, будет обычный мардаун, естественно.

Но неплохо бы эти теги еще как-то особым способом пометить, чтобы и другие случаи их применения не поломать. В идеале, оговоренным хтмл комментом на той же строке. Или особый необычный кейсинг только распознавать, типа Details и только так. Тогда более традиционные details, DETAILS будут обычными, а не специальными.

Что думаете? Лучше, чем ничего. Другие подобные предложения?

**Comment by johnd0e** [comment]
> ...теги [типа 6](https://github.github.com/gfm/#html-block) как самостоятельные и полные, а не блочные конструкции

Но так ведь мы потеряем возможность подсветки парного тега. Или нет?

> чтобы другие "нормальные" случаи их применения не изменить.

Какие другие случаи имеются ввиду? Я честно говоря даже не вижу пока что за "обычные" \<details\> могут вдруг оказаться в markdown, и как их предполагается иначе обрабатывать.

**Comment by nightroman** [comment]
> Но так ведь мы потеряем возможность подсветки парного тега. Или нет?

Потеряем, да. Подумаю над этим.

> Какие другие случаи имеются ввиду?

Когда внутри хтмл, а не маркдаун. GFM хорош, но не единственный диалект. И даже в нем, смотрите примеры по ссылке, внутри тегов то маркаун, то хтмл.

**Comment by johnd0e** [comment]
Я наивно полагал что в схеме можно просто перечислить теги из пункта 6, и с их содержимым всё будет однозначно.

**Comment by nightroman** [comment]
Не совсем понимаю, что имеется в виду, поэтому нечего ответить :)

**Comment by johnd0e** [comment]
Сейчас же html-теги "ловятся" каким-то регэкспом.

Не заглядывая в детали устройства схемы рискну предположить, что можно "забить" в этот регэксп конкретный перечень строк (соответствующий перечислению из пункта 6), и получившиеся блоки парсить как маркдаун.

Насчёт других диалектов.

Насколько я понимаю все основанные на изначальном CommonMark должны обрабатываться именно так.
Для прочих тоже ещё не факт, что это повлечёт какие-либо негативные последствия. И если вдруг да, то наверняка они вообще заслуживают отдельной схемы.

**Comment by johnd0e** [comment]
Не понял о каких атрибутах речь, мы вроде бы их выше никак не затрагивали.

Как именно делать и делать ли вообще это разумеется решать тому кто делает, спору нет. Однако на что именно у вас другой взгляд я тоже не уловил.

**Comment by nightroman** [comment]
Обычные атрибуты на хтмл тегах. Класс и вякое прочее, я даже не силен в этом. Вы лучше знаете, упоминали об атрибутах на div элементах в других топиках.

**Comment by johnd0e** [comment]
Когда я писал "получившиеся блоки парсить как маркдаун" под блоками я имел ввиду то что содержится между открывающим и закрывающим тегом, а не содержимое самих тегов.
