### ISSUE TITLE
Markdown: странное поведение на linux

### ISSUE THREAD

**Issue by ctapmex** [colorer/Colorer-schemes#161]
интересное поведение при просмотре файла https://github.com/elfmz/far2l/blob/master/README.md в linux far2l, видео
[Screencast from 2024-07-11 22-39-23.webm](https://github.com/colorer/Colorer-schemes/assets/1277115/d0ab58d1-558b-4d31-b04d-0e326313b44a)

часть строк начинает подсвечиваться как парные элементы. При этом такого поведения нет на windows.

@nightroman  подскажи, для чего этот блок
```
  <block scheme="Para"
  start="/\M(?{start}%i3;)\S/" end="/(?{end})%PEnd;/"/>
```
зачем i3 , который по сути 0-3 пробелов, помечаем как начало парного блока?

**Comment by nightroman** [comment]
Возможно, не для подсветки как таковой, а для возможности выделить целый блок командой меню колорера "Select block".

**Comment by ctapmex** [comment]
проблема на линукс была связана с изменениями в самом far2l. Откатили, всё стало ок.

>"Select block"
класс, удобно.
