### ISSUE TITLE
<project> tag parsing in xml files

### ISSUE THREAD

**Issue by kong-en-ge** [colorer/Colorer-schemes#162]
If some xml has "project" tag the whole file displays as misformatted

![image](https://github.com/user-attachments/assets/c4125955-62b4-4e97-8aab-f31730670d24)

**Comment by ctapmex** [comment]
There are two root elements in the example here , VisualElements and project, which does not correspond to the xml format.
therefore, the text is highlighted as an error

**Comment by kong-en-ge** [comment]
1. Only Application is the root. It contains VisualElement and project
2. If you change project to anything else the error disappears.

**Comment by ctapmex** [comment]
Yes, that's right. I looked closer.
give an example of a text file and its name

**Comment by ctapmex** [comment]
what is the file name extension? this affects the choice of type recognition scheme

**Comment by kong-en-ge** [comment]
.xml of course

**Comment by ctapmex** [comment]
this file is defined as "ant's build.xml".
you can check this by clicking F11 - FarColorer - List types . The type highlighted in the list is how the plugin defined it.
You must either select the desired other type in the list, or change the settings in proto.hrc. There to reduce the weight in line `<first line weight='5'>/&lt;project\b/</firstline>`

**Comment by kong-en-ge** [comment]
A bit unexpected, but at least clarified :)
