### ISSUE TITLE
smarty-код всё ещё некорректно раскрашивается.

### ISSUE THREAD

**Issue by ctapmex** [colorer/Colorer-schemes#165]
У нас тут недоработка обнаружилась небольшая. Вот этот smarty-код всё ещё некорректно раскрашивается.

```
<script>
    $(document).ready(function() { 
        {if $test}
            $('#action-pending').on('click', function(e) {
                // этот код не должен краситься как код smarty, а он красится!
                window.location = '?action=pending&list=' + list;
                return false;
            });
        {/if}
    }); 
</script>

<style>
    .appeal-content {
        background-color: #eee;
        padding: 10px;
    }

    table.tablesorter tr td table tr.monitor td {
        border-bottom: 2px solid white;
        color: white;
        background-color: red;
        cursor: pointer;
    }
</style>

```

_Originally posted by @unxed in https://github.com/colorer/Colorer-schemes/issues/75#issuecomment-2405961712_

**Comment by ctapmex** [comment]
первое поправил, проверь у себя @unxed
```
	<scheme name="InverseInsertion">
			<block start="/(\})/" end="/(\{)\M\S/" scheme="html"
	
```

а вот со вторым, как ты предлагаешь определять, что это не smarty части ? какой критерий?

**Comment by unxed** [comment]
Вообще говоря, использование фигурных скобок внутри шаблона Smarty напрямую, без замены на {ldelim} и {rdelim} — недокументированная возможность (по крайней мере, я в документации такого не нашёл).

Но по факту, Smarty не считает началом своего тэга открывающую фигурную скобку, если за ней следует пробел, табуляция или перевод строки (может, и ещё какие-то символы, я специально не проверял). Что сильно упрощает кодинг, потому что можно css и jss писать без изменений, ну разве что пробелы не забывать после { ставить, когда в одну строку пишешь.

**Comment by unxed** [comment]
> а вот со вторым, как ты предлагаешь определять, что это не smarty части ? какой критерий?

Это где literal? ну всё что внутри literal — не smarty-код, оно должно интерпретироваться как обычный html/css/js

**Comment by unxed** [comment]
> проверь у себя

а это куда вписать?

**Comment by ctapmex** [comment]
> а это куда вписать?

base/hrc/inet/smarty.hrc

**Comment by unxed** [comment]
а, вижу! проверил. ушла бага!

**Comment by unxed** [comment]
и будто бы даже не сломалось ничего!

**Comment by unxed** [comment]
А с {literal} получится что-нибудь сделать?

**Comment by ctapmex** [comment]
пока получилось только так
![image](https://github.com/user-attachments/assets/c6c432ec-5126-49b8-bb1c-80db97648691)

**Comment by ctapmex** [comment]
либо весь блок помечается цветом вложенного.
иначе не получается.  больше времени на это пока не хочу тратить

**Comment by unxed** [comment]
В смысле, всё, что внутри literal, не раскрашивается вовсе? Да, наверное так лучше чем было. Всё-таки это не самая частая конструкция. По крайней мере, теперь её содержимое выделяется визуально как «что-то другое», это хорошо.

**Comment by ctapmex** [comment]
1. все что внутри literal пытается раскраситься как html
2. сам `{literal}` не выделяется цветом , как например if  выше на картинке

либо  весь блок `{literal}` - `{/literal}` помечается цветом вложенного блока, как if

если что-то из этого устраивает - добавлю

**Comment by unxed** [comment]
А можно плз изменения .hrc для того и другого варианта, чтоб я сам покрутил-попробовал?

**Comment by unxed** [comment]
Чёрт, кажется, я ещё один баг поймал

```
{if $image.is_img && ($image.type == 'l')}
<a rel=lightbox target="_blank" href="{$image.uri}"><img
    data-src="{$image.preview_uri}"
    style="float: left; padding-right: 1em;"
    class="lazy"
/></a>
{/if}
```

![изображение](https://github.com/user-attachments/assets/e73d78ad-121e-4261-8976-070d5e886c6c)

**Comment by unxed** [comment]
При этом из-за непостижимой магии добавление четырёх пробелов решает проблему:
```
{if $image.is_img && ($image.type == 'l')}
<a rel=lightbox target="_blank" href="{$image.uri}"><img
    data-src="{$image.preview_uri}"
    style="float: left; padding-right: 1em;"
    class="lazy"
    /></a>
{/if}
```

Так что я просто переверстал это, чтоб красное в глаза не лезло. Но если будет возможность поправить — было бы здорово поправить, конечно.

**Comment by unxed** [comment]
И ещё вот с такими конструкциями проблема есть: вторые if'ы красным показываются:
```
{if $x}
    <form>
{/if}
...
{if $x}
    </form>
{/if}
```

Обойти можно так:
```
{if $x}
    {"<"}form>
{/if}
...
{if $x}
    {"<"}/form>
{/if}
```
