### ISSUE TITLE
`s[][]` in shell script garbles colors

### ISSUE THREAD

**Issue by AlfonZ42** [colorer/Colorer-schemes#4]
Consider following script:

``` bash
#!bash
# comment1
echo "search" | perl -pe "s[search][replace]"
# comment2
```

comment1 is colored correctly (region info says `def:Comment`). comment2 (and all that follows it) is not (region info says `shell:string`).
Similarly for `s()()`, `s<><>`, `s{}{}`.

Tested with Far v3.0.3525, FarColorer v1.2.1.2.

**Comment by ctapmex** [comment]
fixed in https://github.com/colorer/Colorer-schemes/releases/tag/v1.2.0.36
