### ISSUE TITLE
C++11: curly brackets should be allowed in expressions

### ISSUE THREAD

**Issue by yeputons** [colorer/Colorer-schemes#78]
Example of wrong highlighting in Far Manager:

![image](https://user-images.githubusercontent.com/1297325/61042536-aea5b380-a3d4-11e9-803c-80213b13281c.png)

Another example is list initialization: `some_class({1, 2, 3}, {4, 5, 6})`.

I suggest the following quick hack to [`cpp.hrc`](https://github.com/colorer/Colorer-schemes/blob/master/hrc/hrc/base/cpp.hrc):

```
*** cpp.hrd.old	Thu Jul 11 12:02:38 2019
--- cpp.hrc.new	Thu Jul 11 12:02:55 2019
***************
*** 79,84 ****
--- 79,87 ----
     region11="c:StructureSymbol"
    />
    
+   <!-- Hack for lambdas and list initialization -->
+   <block start="/(\{)/" end="/(\})/" scheme="Expression"
+         region00="def:SymbolStrong" region01="def:PairStart" region10="def:SymbolStrong" region11="def:PairEnd"/>
  
    <!-- !!EE: Block #2 template support -->
    <!-- Colorer 4:
```

Result:

![image](https://user-images.githubusercontent.com/1297325/61042717-0b08d300-a3d5-11e9-95ab-dd9850633969.png)

**Comment by alabuzhev** [comment]
![image](https://user-images.githubusercontent.com/11453922/69102526-a3395780-0a5a-11ea-9287-0f36856ae3a0.png)
