### ISSUE TITLE
Неправильно выбирает схему для readme-gen.lua

### ISSUE THREAD

**Issue by z0hm** [colorer/Colorer-schemes#94]
Исходит из readme в имени, а не из расширения lua.

**Comment by ctapmex** [comment]
нужен пример, или первые несколько строк файла. и какой тип выбирается.
если взять произвольный lua файл и переименовать в readme-gen.lua , то он определяется как lua.

**Comment by ctapmex** [comment]
@z0hm это еще актуально?

**Comment by ctapmex** [comment]
для plain  text срабатывает регулярка для подстроки readme. и для lua срабатывает по расширению. других условий нет, поэтому вес одинаковый. выбирается первый - это plain text
