### ISSUE TITLE
Problem with << operator in sh script

### ISSUE THREAD

**Issue by PavelK115** [colorer/Colorer-schemes#95]
Hi,
I found that colorer in Far editor has problem to recognize << (left shift operator) in sh script. This operator is allowed in arithmetic evaluation. For example in the file test.sh containing

echo Hello
X=$(( 31>>3 ))   # right shift operator is ok
X=$(( 1<<3 ))    # left shift operator confuses colorer
echo X=${X}

the rest of the file after << is not recognized by the colorer.

**Comment by ctapmex** [comment]
fixed in https://github.com/colorer/Colorer-schemes/releases/tag/v1.2.0.36
