### ISSUE TITLE
bug with .c code processing

### ISSUE THREAD

**Issue by unxed** [colorer/Colorer-schemes#97]
Sample: [unix.zip](https://github.com/colorer/Colorer-schemes/files/5322538/unix.zip)
Code itself is correct, taken from latest info-zip source tree.
![Снимок экрана в 2020-10-04 04-32-36](https://user-images.githubusercontent.com/1151423/95004942-caf5c780-05fa-11eb-848e-e6ffaeb416bb.png)

**Comment by ivanshatsky** [comment]
The given code isn't correct, opening and closing braces count isn't equal.
Most probably the correct code line should be
`    if ((dirp = malloc(sizeof(DIR))) != NULL) {`
and such a line doesn't produce any coloring errors.

**Comment by unxed** [comment]
Looks like the code itself is buggy.
```
    if ((dirp = malloc(sizeof(DIR)) != NULL) {
```
probably should be
```
    if (dirp = malloc(sizeof(DIR)) != NULL) {
```

Strange, but it is from official InfoZIP sources:
https://deac-ams.dl.sourceforge.net/project/infozip/UnZip%206.x%20%28latest%29/UnZip%206.0/unzip60.zip

Anyway, not a colorer problem. Closing.
